'use strict';
const $=id=>document.getElementById(id);
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=s=>{try{const u=new URL(s);return u.protocol==='https:'?u.href:'#';}catch{return '#';}};
const node=(id,title,type,detail)=>({id,title,type,detail});
const teaching={id:'fruit',title:'关联路径示意',kind:'teaching',question:'水果、运动和心情，怎么连起来？',description:'把几张信息卡连起来，理解“沿线索继续找”。关系为教学编排，不是健康建议，也不是已验证的因果链。',limitations:['节点和关系均为手工编排，仅解释检索机制。','水果、运动与心情之间不能仅凭这些关系推出健康因果结论。','无模型运行、无实际检索成本；不与真实实验效果混算。'],modes:{flat:{steps:[{title:'一次找相似内容',explanation:'单轮演示只取回与“水果”直接相关的两张卡；这里是脚本安排。',nodes:[node('fruit-q','从水果出发','query','这个问题是教学脚本的起点。'),node('fruit-a','水果种类','evidence','这张示意卡列出香蕉、苹果等词语。它与“水果”的字面关联强。'),node('fruit-b','水果的颜色','evidence','这张示意卡描述外观。演示中，初次检索在这里停止。')],edges:[{from:'fruit-q',to:'fruit-a',type:'semantic'},{from:'fruit-q',to:'fruit-b',type:'semantic'}]}],metrics:{label:'教学路径',display:'1 轮',note:'从初始问题找一批材料，然后停下。'}},full:{steps:[{title:'先找到一个可追的线索',explanation:'读到“营养成分”，就有了下一次要找的内容。',nodes:[node('fruit-q','从水果出发','query','教学起点。下面的关系由作者编排，不来自医学实验。'),node('fruit-n','营养成分','evidence','示意关系：水果卡提到营养成分。检索下一步可以围绕这个中间概念展开。')],edges:[{from:'fruit-q',to:'fruit-n',type:'semantic'}]},{title:'沿中间概念继续找',explanation:'第二跳围绕“运动供能”展开，材料未必重复出现“水果”二字。',nodes:[node('fruit-e','运动供能','evidence','示意关系：从营养成分联想到运动供能。这是关联路径，不表示每一种水果都有特定运动效果。')],edges:[{from:'fruit-n',to:'fruit-e',type:'association'}]},{title:'找到更远的相关材料',explanation:'路径通向“运动体验与心情”，但关系相连不等于因果成立。',nodes:[node('fruit-m','运动体验与心情','hit','示意终点。把材料串起来后，仍需检查每条关系和适用条件，不能直接给出健康结论。')],edges:[{from:'fruit-e',to:'fruit-m',type:'association'}]}],metrics:{label:'教学路径',display:'3 轮',note:'读中间材料，再沿着新线索查找。'}}}};
let scenarios=[teaching],current=teaching,mode='full',step=0,timer=null,selected=null;
const modeData=()=>current.modes[mode];
function stop(){clearInterval(timer);timer=null;$('autoplay').textContent='自动播放';$('autoplay').setAttribute('aria-pressed','false');}
function selectScenario(id){stop();current=scenarios.find(s=>s.id===id)||teaching;step=current.kind==='real'?1:0;selected=null;render();}
function setMode(value){stop();mode=value;step=0;selected=null;render();}
function advance(){if(step<modeData().steps.length){step++;selected=null;renderBoard();}if(step>=modeData().steps.length)stop();}
function render(){
 $('scenarios').innerHTML=scenarios.map(s=>`<button class="scenario-tab" data-scenario="${escapeHTML(s.id)}" aria-pressed="${s.id===current.id}">${s.id==='fruit'?'关联示意':s.id==='H174030'?'引文扩展':'路径偏移'}<span class="tab-sub">${s.kind==='real'?escapeHTML(s.id):'教学案例'}</span></button>`).join('');
 document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>selectScenario(b.dataset.scenario));
 $('question').textContent=current.question;$('kind').textContent=current.kind==='real'?'真实裁定实验回放':'关联路径示意';$('description').textContent=current.description;
 document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));
 $('replay-label').textContent=current.kind==='real'?'2026.09 实验记录 · 非实时推理':'脚本演示 · 不调用模型';
 $('comparison-note').textContent=current.kind==='real'?'以下为此案例的完整运行记录。引文恢复不是估价准确率；更多线索也意味着更多读取成本。':'轮数来自编排好的教学路径，不是模型性能评测。多跳不保证每次都更好。';
 $('metric-cards').innerHTML=['flat','full'].map(k=>{const m=current.modes[k].metrics;return `<article class="metric-card ${k}"><h3>${k==='flat'?'单轮检索':'多跳检索'}</h3><span class="big-value">${m.display?escapeHTML(m.display):`${m.hits} / ${m.total}`}</span><span class="big-label">${escapeHTML(m.label)}</span>${m.inputTokens!==undefined?`<div class="metric-row"><span>模型输入 tokens<b>${m.inputTokens.toLocaleString()}</b></span><span>模型调用<b>${m.calls} 次</b></span><span>取回片段<b>${m.chunks} 个</b></span></div><p>${m.outputTokens} 输出 tokens · ${m.documents} 份文档</p>`:`<p>${escapeHTML(m.note)}</p>`}</article>`}).join('');
 $('limitations').innerHTML=`<ul>${(current.limitations||[]).map(l=>`<li>${escapeHTML(l)}</li>`).join('')}</ul>${current.sourceUrl?`<a target="_blank" rel="noopener noreferrer" href="${safeURL(current.sourceUrl.replace('/ruling/','/api/ruling/'))}">打开 CBP 原始裁定</a>`:''}`;
 renderBoard();
}
function visibleSteps(){return modeData().steps.slice(0,step);}
function chosenNodes(s){if(current.kind!=='real')return s.nodes;const all=modeData().steps.flatMap(t=>t.edges||[]);const linked=new Set(all.filter(e=>e.type==='citation').flatMap(e=>[e.from,e.to]));const q=s.nodes.filter(n=>n.type==='query');const docs=s.nodes.filter(n=>n.type!=='query');docs.sort((a,b)=>(Number(linked.has(b.id))*4+Number(b.labelHit)*2)-(Number(linked.has(a.id))*4+Number(a.labelHit)*2));const limit=mode==='flat'?3:2;const picked=[];const seen=new Set();for(const n of docs){const doc=n.chunkId?n.chunkId.split(':')[0]:n.title;if(!seen.has(doc)){picked.push(n);seen.add(doc);}if(picked.length===limit)break;}if(picked.length<limit){for(const n of docs){if(!picked.includes(n))picked.push(n);if(picked.length===limit)break;}}return [...q,...picked];}
function nodeHTML(n){return `<button class="node ${n.type==='query'?'query':''} ${n.type==='hit'?'is-terminal':''} fresh" data-node="${escapeHTML(n.id)}" aria-pressed="false"><span class="node-type">${n.type==='query'?'问一个问题':n.labelHit?'原裁定引文命中':current.kind==='real'?'裁定片段':'教学信息卡'}</span><span class="node-title">${escapeHTML(n.title)}${n.chunkId?`<small class="chunk-number">片段 ${escapeHTML(n.chunkId.split(':').at(-1))}</small>`:''}</span><span class="node-arrow">↗</span></button>`;}
function renderBoard(){
 const steps=visibleSteps();const initial=modeData().steps[0].nodes.find(n=>n.type==='query');
 $('nodes').innerHTML=step===0?`<div class="node-column">${nodeHTML(initial)}</div><div class="node-column ghost">下一条线索<br>等待展开</div>`:steps.map(s=>`<div class="node-column">${chosenNodes(s).map(nodeHTML).join('')}</div>`).join('');
 if(step>0&&step<modeData().steps.length)$('nodes').insertAdjacentHTML('beforeend','<div class="node-column ghost">下一轮证据<br>等待展开</div>');
 document.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>showNode(findNode(b.dataset.node)));
 $('step-label').textContent=step===0?'初始状态':`${step} / ${modeData().steps.length} 轮 · ${steps.at(-1).title}`;
 $('previous').disabled=step===0;$('next').disabled=step>=modeData().steps.length;$('next').innerHTML=step===0?'展开第一轮 <span>↗</span>':step>=modeData().steps.length?'本次路径已走完':'展开下一轮 <span>↗</span>';
 $('autoplay').disabled=step>=modeData().steps.length;
 $('step-description').textContent=step===0?'点“展开第一轮”，亲手展开第一轮。':steps.at(-1).explanation;
 if(step===0){$('detail-title').textContent='从一项问题出发';$('detail-body').innerHTML='<p>每张单证卡均可展开查看。<br>先展开一轮，再看看线索来自哪里。</p><p>可以随时切换单轮与多跳，比较同一问题的两条路径。</p>';}else showRound(steps.at(-1));
 requestAnimationFrame(drawEdges);
}
function findNode(id){return modeData().steps.flatMap(s=>s.nodes).find(n=>n.id===id);}
function showNode(n){if(!n)return;selected=n.id;document.querySelectorAll('[data-node]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.node===n.id)));$('detail-title').textContent=n.title;$('detail-body').innerHTML=`${n.chunkId?`<span class="detail-tag">${escapeHTML(n.chunkId)}</span>`:''}<p>${escapeHTML(n.detail)}</p>${n.excerpt?`<blockquote lang="en">${escapeHTML(n.excerpt)}</blockquote>`:''}${n.date?`<p>裁定日期：${escapeHTML(n.date)}${n.sourceCharacterRange?`<br>原文字符位置：${n.sourceCharacterRange.join('–')}`:''}</p>`:''}${n.url?`<a href="${safeURL(n.apiUrl||n.url.replace('/ruling/','/api/ruling/'))}" target="_blank" rel="noopener noreferrer">查看官方原始记录 ↗</a>`:''}${n.labelHit?'<p>“命中”只表示取回原裁定引用过的文档，不表示其已经充分支持判断。</p>':''}<button class="back-detail">返回本轮材料</button>`;$('detail-body').querySelector('.back-detail').onclick=()=>{selected=null;showRound(visibleSteps().at(-1));};}
function showRound(s){if(!s)return;document.querySelectorAll('[data-node]').forEach(b=>b.setAttribute('aria-pressed','false'));$('detail-title').textContent=s.title;const docs=s.nodes.filter(n=>n.type!=='query');$('detail-body').innerHTML=`<p>${escapeHTML(s.explanation)}</p>${current.kind==='real'?`<p>本轮取回 ${docs.length} 个片段。画布按完整轨迹挑选关键节点，包含后续被引用的片段；这不是当轮实时排序。下面保留全部片段。</p><details class="all-docs"><summary>展开本轮全部 ${docs.length} 个片段</summary>${docs.map(n=>`<button data-detail-node="${escapeHTML(n.id)}">${escapeHTML(n.chunkId||n.title)}${n.labelHit?' · 引文命中':''}</button>`).join('')}</details>`:'<p>点选卡片，检查每条关系的含义。</p>'}`;$('detail-body').querySelectorAll('[data-detail-node]').forEach(b=>b.onclick=()=>showNode(findNode(b.dataset.detailNode)));}
function drawEdges(){const board=$('board'),svg=$('connections');svg.setAttribute('width',board.scrollWidth);svg.setAttribute('height',board.scrollHeight);svg.innerHTML='<defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10z" fill="#768d8a"/></marker></defs>';const br=board.getBoundingClientRect();const elements=[...document.querySelectorAll('[data-node]')];for(const e of visibleSteps().flatMap(s=>s.edges||[])){const a=elements.find(x=>x.dataset.node===e.from),b=elements.find(x=>x.dataset.node===e.to);if(!a||!b)continue;const ar=a.getBoundingClientRect(),tr=b.getBoundingClientRect();let x1=ar.right-br.left+board.scrollLeft,y1=ar.top+ar.height/2-br.top+board.scrollTop,x2=tr.left-br.left+board.scrollLeft,y2=tr.top+tr.height/2-br.top+board.scrollTop;const same=Math.abs(ar.left-tr.left)<5;if(same){x1=ar.right-br.left+board.scrollLeft;y1=ar.top+ar.height/2-br.top+board.scrollTop;x2=tr.right-br.left+board.scrollLeft;y2=tr.top+tr.height/2-br.top+board.scrollTop;}const branchX=Math.max(x1,x2)+16;const d=same?`M${x1},${y1} C${branchX},${y1} ${branchX},${y1+12} ${branchX},${y1+20} L${branchX},${y2-12} Q${branchX},${y2} ${x2},${y2}`:`M${x1},${y1} C${(x1+x2)/2},${y1} ${(x1+x2)/2},${y2} ${x2},${y2}`;const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);p.setAttribute('fill','none');p.setAttribute('stroke',e.type==='semantic'?'#9baaa8':'#486b66');p.setAttribute('stroke-width','2');if(e.type==='semantic')p.setAttribute('stroke-dasharray','5 5');p.setAttribute('marker-end','url(#arrow)');svg.append(p);}}
$('previous').onclick=()=>{stop();if(step>0){step--;selected=null;renderBoard();}};$('next').onclick=advance;$('reset').onclick=()=>{stop();step=0;selected=null;renderBoard();};$('autoplay').onclick=()=>{if(timer){stop();return;}advance();if(step<modeData().steps.length){$('autoplay').textContent='暂停播放';$('autoplay').setAttribute('aria-pressed','true');timer=setInterval(advance,2200);}};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));window.addEventListener('resize',drawEdges);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});render();
fetch('data.json').then(r=>{if(!r.ok)throw Error('数据读取失败');return r.json();}).then(data=>{scenarios=[teaching,...data.scenarios];$('research-sources').innerHTML=(data.sources||[]).map(s=>`<a href="${safeURL(s.url)}" target="_blank" rel="noopener noreferrer">${escapeHTML(s.title)} ↗</a>`).join('');const a=data.aggregate;if(a){$('aggregate-summary').innerHTML=`<h3>把两个案例放回全样本</h3><p>${a.cases} 个案例 × ${a.methods} 种方法，共 ${a.runs} 份输出。多跳相对单轮：${a.improved} 案增加、${a.worse} 案减少、${a.tied} 案持平。合并库内引文恢复率从 ${a.flatRecall}%（${a.flatHits}/${a.eligibleCitationPairs}）到 ${a.fullRecall}%（${a.fullHits}/${a.eligibleCitationPairs}），模型输入约为 ${a.inputRatio} 倍。</p><p>${escapeHTML(a.definition)}</p><ul>${a.limitations.map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ul>`;}selectScenario('H174030');}).catch(()=>{$('description').textContent+=' 真实实验数据暂未加载，可刷新重试；教学示例仍可使用。';});
