import assert from 'node:assert/strict';
import {CorpusSearch} from './retrieval-engine.js';
const docs=[{id:'A',title:'Electric toothbrush',jurisdiction:'US'},{id:'B',title:'Referenced motor ruling',jurisdiction:'US'},{id:'C',title:'中国商品材料',jurisdiction:'CN'}];
const chunks=[{id:'a',doc_id:'A',text:'electric toothbrush motor references B',refs:['B','OUTSIDE']},{id:'b',doc_id:'B',text:'motor electric appliance',refs:[]},{id:'c',doc_id:'C',text:'中国商品归类与材料要求',refs:[]}];
const e=new CorpusSearch({docs,chunks});
assert.equal(e.search('电动牙刷')[0].id,'a','bilingual aliases retrieve actual English text');
assert.equal(e.search('zznonexistentzz').length,0,'unseen query cannot return invented results');
assert.ok(e.search('商品',{jurisdiction:'CN'}).every(c=>c.doc_id==='C'),'jurisdiction filter');
assert.ok(e.search('electric',{exclude:['a']}).every(c=>c.id!=='a'),'excluded evidence');
const result=e.follow(chunks[0],'motor');
assert.ok(result.some(c=>c.id==='b'&&c.relation==='reference'&&c.from==='a'),'explicit known reference creates edge');
assert.ok(!result.some(c=>c.doc_id==='OUTSIDE'),'unavailable references never fabricated');
assert.ok(result.filter(c=>c.relation==='query').every(c=>c.reason.includes('不代表原文存在引用关系')),'query expansion not called citation');
console.log('7 retrieval behavior assertions passed');
const scoped=new CorpusSearch({docs:[{id:'us',jurisdiction:'US',title:''},{id:'cn',jurisdiction:'CN',title:''}],chunks:[{id:'us1',doc_id:'us',text:'electric toothbrush'},{id:'cn1',doc_id:'cn',text:'electric motor'}]});
assert.equal(scoped.search('electric toothbrush',{jurisdiction:'CN'})[0]?.id,'cn1','anchors only computed inside requested jurisdiction');
const longRef=new CorpusSearch({docs:[{id:'root',title:''},{id:'target',title:''},...Array.from({length:35},(_,i)=>({id:'noise'+i,title:'specialquery'}))],chunks:[{id:'root1',doc_id:'root',text:'reference target',refs:['target']},{id:'entry',doc_id:'target',text:'general introduction'},{id:'later',doc_id:'target',text:'specialquery in later paragraph'},...Array.from({length:35},(_,i)=>({id:'noise'+i,doc_id:'noise'+i,text:'specialquery specialquery'}))]});
assert.equal(longRef.follow(longRef.chunks[0],'specialquery').find(x=>x.relation==='reference').id,'later','reference target locally ranked beyond global top thirty');
assert.match(longRef.follow(longRef.chunks[0],'absentword').find(x=>x.relation==='reference').reason,/未命中本轮查询/,'unmatched entry explicitly labelled');
console.log('3 scope and local reference ranking regressions passed');
