import {CorpusSearch,expandQuery} from './retrieval-engine.js';
const $=s=>document.querySelector(s),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=s=>{try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch{return '#'}};
let engine,corpus,selected=null,model=false,busy=false;
let state={query:'',rounds:[],conditions:{}};
try{const saved=JSON.parse(localStorage.getItem('boxu-workspace-v1'));if(saved&&Array.isArray(saved.rounds))state=saved}catch{}
const save=()=>{try{localStorage.setItem('boxu-workspace-v1',JSON.stringify(state))}catch{}};
function route(){if(location.hash==='#query'){location.hash='workbench';requestAnimationFrame(()=>$('#query').focus());return}const id=location.hash.slice(1)||'home';document.querySelectorAll('.route').forEach(e=>e.hidden=e.id!==id);document.querySelectorAll('[data-route]').forEach(e=>e.classList.toggle('active',e.dataset.route===id));if(!['home','solutions','workbench'].includes(id))location.hash='home'}
addEventListener('hashchange',route);document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('svg [role=button]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}))}});route();
function conditions(){return {destination:$('#destination').value,date:$('#trade-date').value,origin:$('#origin').value,commodity:$('#commodity').value}}
function getChunk(id){return engine.chunks.find(c=>c.id===id)}
function snippet(text,tokens=[]){let start=0;const lower=text.toLowerCase(),hit=tokens.filter(t=>t.length>2).map(t=>lower.indexOf(t.toLowerCase())).filter(i=>i>=0).sort((a,b)=>a-b)[0];if(hit>100)start=hit-70;return (start?'…':'')+text.slice(start,start+360)+(text.length>start+360?'…':'')}
function render(){
 $('#round-count').textContent=`${state.rounds.length} 轮`;
 if(!state.rounds.length)return;
 $('#timeline').innerHTML=state.rounds.map((r,i)=>`<article class="round" data-round="${i}"><div class="round-heading"><span class="round-number">${i+1}</span><h3>${escape(r.query)}</h3></div><div class="round-meta">${escape(r.time)} · ${r.results.length} 个片段 · ${new Set(r.results.map(c=>c.doc_id)).size} 份文件</div><ul class="events">${r.events.map(x=>`<li>${escape(x)}</li>`).join('')}</ul>${r.results.length?r.results.map(c=>{const d=engine.docs.get(c.doc_id)||{};return `<article class="result ${r.selected===c.id?'selected':''}"><div class="result-head"><button class="result-title" data-open="${escape(c.id)}">${escape(d.title||d.id)}</button><span class="score">${c.relation==='reference'?'原文引用':'词项得分 '+Number(c.score||0).toFixed(2)}</span></div><div class="result-meta">${escape(d.jurisdiction)} · ${escape(d.date||'日期见来源')} · ${escape(c.id)}</div><p class="excerpt">${escape(snippet(c.text,c.matched))}</p><div class="result-reason">${escape(c.reason)}</div><div class="result-actions"><button data-open="${escape(c.id)}">查看原文</button><button ${busy?'disabled':''} class="${r.selected===c.id?'chosen':''}" data-select="${escape(c.id)}" data-round="${i}">${r.selected===c.id?'已选为下一跳依据':'选择并继续查证'}</button></div></article>`}).join(''):'<div class="notice">当前资料库没有命中。请改用具体商品、费用、英文术语或裁定编号；未命中不代表不存在相关规定。</div>'}<div class="answer"><h3>${r.model?'模型回答':'证据检索记录'}</h3><p>${escape(r.answer)}</p></div>${r.rateNote?`<p class="notice">${escape(r.rateNote)}</p>`:''}</article>`).join('');
 $('#session-subtitle').textContent=state.query;save();
}
function source(id){const c=getChunk(id),d=c&&engine.docs.get(c.doc_id);if(!d)return;const text=d.text||c.text;let start=c.start,end=c.end;if(!Number.isInteger(start)||text.slice(start,end)!==c.text){start=text.indexOf(c.text);end=start+c.text.length}const contextStart=Math.max(0,start-450),contextEnd=Math.min(text.length,end+600);const content=start>=0?escape(text.slice(contextStart,start))+'<mark>'+escape(text.slice(start,end))+'</mark>'+escape(text.slice(end,contextEnd)):escape(c.text);
 $('#source-view').innerHTML=`<div class="source-heading"><h3>${escape(d.title)}</h3><a href="${escape(safeURL(d.source_url))}" target="_blank" rel="noopener noreferrer">打开官方来源</a></div><div class="source-meta">${escape(d.jurisdiction)} · ${escape(d.date)}<br>片段 ${escape(c.id)}${start>=0?' · 原文字符 '+start+'–'+end:''}</div>${d.verified_rate_row?`<section class="verified-rate"><h3>已核验税则条目</h3><strong>${escape(d.verified_rate_row.code)} · ${escape(d.verified_rate_row.label)}</strong><dl><dt>表列最惠国税率</dt><dd>${escape(d.verified_rate_row.mfn_rate)}%</dd><dt>表列普通税率</dt><dd>${escape(d.verified_rate_row.general_rate)}%</dd></dl><p>${escape(d.verified_rate_row.scope_note)} 实际适用仍需核对原产地、日期、优惠资格及后续调整。</p></section>`:''}${d.status?.numeric_rate_extraction==='not_validated'?'<p class="notice">该税则页为 PDF 文本抽取，多列表格顺序尚未完整核验。请打开官方原页确认列标题和数值对应，勿直接套用。</p>':''}<div class="source-text">${contextStart?'…\n':''}${content}${contextEnd<text.length?'\n…':''}</div><p class="muted">高亮对应选中片段。文档引用关系不表示因果关系或自动适用。</p>`;
 $('.source-panel').classList.add('open');renderPath();
}
function renderPath(){const choices=state.rounds.map((r,i)=>({r,i,c:r.selected&&getChunk(r.selected)})).filter(x=>x.c);if(!choices.length){$('#path-view').innerHTML='<p class="muted">选择一个片段作为下一跳依据。</p>';return}const height=choices.length*100+10;$('#path-view').innerHTML=`<div class="path"><h3>跨文件证据链</h3><svg class="evidence-graph" viewBox="0 0 300 ${height}" role="img" aria-label="已选择文件及其关系"><defs><marker id="arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="#4b858a"/></marker></defs>${choices.map(({r,i,c},k)=>{const y=k*100+15,rel=r.results.find(x=>x.id===c.id)?.relation;return `${k?`<g class="graph-edge" data-edge="${i}" tabindex="0" role="button" aria-label="查看跳转原因"><path d="M25 ${y-55} L25 ${y}" stroke="#4b858a" stroke-width="2" ${rel==='reference'?'':'stroke-dasharray="4 3"'} marker-end="url(#arrow)"/><rect x="34" y="${y-42}" width="236" height="27" fill="#f3f7f9"/><text x="40" y="${y-25}">${rel==='reference'?'明确引用 · 点击查看原因':'查询关联 · 非引用关系'}</text></g>`:''}<g data-open="${escape(c.id)}" tabindex="0" role="button" aria-label="打开 ${escape(c.doc_id)} 原文"><rect x="7" y="${y}" width="286" height="44" rx="4" fill="#e8f1f5" stroke="#b8ccd6"/><circle cx="25" cy="${y+22}" r="5" fill="#087c82"/><text x="40" y="${y+18}">第 ${i+1} 轮 · ${escape(c.doc_id.slice(0,30))}</text><text x="40" y="${y+34}" class="graph-sub">${escape((engine.docs.get(c.doc_id)?.title||'').slice(0,29))}</text></g>`}).join('')}</svg><p class="muted">实线为原文引用；虚线为查询关联。节点可打开对应片段。</p></div>`}
function rateNote(query){if(!/税率|税额|tariff|duty|rate/i.test(query))return '';const c=state.conditions,missing=[!c.destination&&'进口地区',!c.date&&'进口日期',!c.origin&&'原产地',!c.commodity&&'商品属性'].filter(Boolean);return `税率核验：${missing.length?'尚缺'+missing.join('、')+'。':'已记录地区、日期、原产地与商品属性，仍须核定税号及政策适用条件。'}历史裁定中的税率不能直接套用于本次进口；以下片段仅供查证，未计算适用税率或税额。`}
async function modelAnswer(round){if(!model||!round.results.length)return;round.model=true;round.answer='';render();try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:round.query+'\n适用条件：'+JSON.stringify(state.conditions),evidence:round.results.map(c=>({id:c.id,title:engine.docs.get(c.doc_id)?.title,url:engine.docs.get(c.doc_id)?.source_url,text:c.text}))})});if(!response.ok)throw Error('模型服务返回 '+response.status);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true}).replace(/\r\n/g,'\n');let ix;while((ix=buffer.indexOf('\n\n'))>=0){const part=buffer.slice(0,ix);buffer=buffer.slice(ix+2);const event=part.match(/^event:\s*(.+)$/m)?.[1],raw=part.split('\n').filter(l=>l.startsWith('data:')).map(l=>l.slice(5).trim()).join('\n');if(!raw)continue;const data=JSON.parse(raw);if(event==='error')throw Error(data.message||'模型服务中断');if(event==='delta'){round.answer+=data.text||'';render()}}}if(!round.answer)throw Error('模型未返回回答');round.events.push('模型回答完成；检索事件和引用片段已保留。')}catch(error){round.answer+=(round.answer?'\n\n':'')+'模型回答未完成：'+error.message+'。上方检索证据仍可查看。';round.events.push('模型服务失败，未将检索记录替换为模拟回答。')}render()}
async function run(query,from=null){if(busy||!engine)return;query=query.trim();if(!query&&!from)return;busy=true;$('#search-button').disabled=true;$('#follow-form').hidden=true;const queryText=query||state.query;const start=performance.now(),opts={jurisdiction:$('#jurisdiction').value};const results=from?engine.follow(from,queryText,opts):engine.search(queryText,opts);const round={query:queryText,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}),results,selected:null,events:[`查询：${queryText}`,`实际词项扩展：${expandQuery(queryText)}`,from?`从片段 ${from.id} 继续；已收录引用 ${[...new Set((from.refs||[]).filter(id=>engine.docs.has(String(id))))].length} 份。`:'在所选范围中检索已收录的原文片段。',`检索完成：${results.length} 个片段，耗时 ${Math.round(performance.now()-start)} 毫秒。`],model:false,answer:results.length?`本轮检索找到 ${results.length} 个片段，来自 ${new Set(results.map(x=>x.doc_id)).size} 份文件。请核对商品事实、地区与时间后选择一条依据继续。这里呈现检索记录，尚未生成法律或税率结论。`:'未找到可用片段，未生成结论。',rateNote:rateNote(queryText)};state.rounds.push(round);render();await modelAnswer(round);busy=false;$('#search-button').disabled=false;render();document.querySelector(`[data-round="${state.rounds.length-1}"]`)?.scrollIntoView({block:'start',behavior:'smooth'})}
$('#query-form').addEventListener('submit',e=>{e.preventDefault();if(busy)return;const q=$('#query').value.trim();if(!q)return;state={query:q,rounds:[],conditions:conditions()};selected=null;$('#path-view').innerHTML='';run(q)});
$('#follow-form').addEventListener('submit',e=>{e.preventDefault();if(!selected)return;run($('#follow-query').value,selected)});
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-open],[data-edge]');if(!b)return;if(b.dataset.preset){$('#query').value=b.dataset.preset;location.hash='workbench';$('#query').focus()}if(b.dataset.open)source(b.dataset.open);if(b.dataset.select&&!busy){const i=Number(b.dataset.round);state.rounds=state.rounds.slice(0,i+1);state.rounds[i].selected=b.dataset.select;selected=getChunk(b.dataset.select);render();source(selected.id);$('#selection-summary').textContent='依据：'+engine.docs.get(selected.doc_id).title+'。改选早前轮次会清除其后的结果。';$('#follow-query').value=state.rounds[i].query;$('#follow-form').hidden=false;$('#follow-form').scrollIntoView({block:'center',behavior:'smooth'})}if(b.dataset.edge){const r=state.rounds[Number(b.dataset.edge)],c=r.results.find(x=>x.id===r.selected);source(c.id);$('#source-view').insertAdjacentHTML('afterbegin',`<p class="notice">${escape(c.reason)}</p>`)}});
$('#close-source').onclick=()=>$('.source-panel').classList.remove('open');$('#clear-selection').onclick=()=>{selected=null;$('#follow-form').hidden=true};$('#new-session').onclick=()=>{if(busy)return;state={query:'',rounds:[],conditions:{}};save();location.reload()};$('#export-session').onclick=()=>{const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString(),mode:model?'model-service-and-local-retrieval':'local-corpus-retrieval'},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='泊序查证记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
async function init(){try{const response=await fetch('corpus.json');if(!response.ok)throw Error('资料库加载失败');corpus=await response.json();engine=new CorpusSearch(corpus);$('#corpus-status').textContent=`${engine.docs.size} 份资料可检索`;$('#source-summary').textContent=`${engine.docs.size} 份来源资料 / ${engine.chunks.length} 个原文片段。收录范围以解决方案页说明为准。`;const jurisdictions=[...new Set(corpus.docs.map(d=>d.jurisdiction))];$('#jurisdiction').innerHTML='<option value="">全部已收录资料</option>'+jurisdictions.map(j=>`<option>${escape(j)}</option>`).join('');$('#coverage').innerHTML=`<p>当前收录 ${engine.docs.size} 份材料、${engine.chunks.length} 个片段：美国 CROSS 既有估价裁定、中国已整理归类决定与部分 2026 税则原文页。具体日期和出处随片段显示。</p><p>暂未接入统计局数据、完整海关贸易数据库、完整税率变更表和私人资料。收录不代表覆盖全部现行规定；中国旧归类决定的现行效力需另核。</p>`;$('#search-button').disabled=false;if(state.rounds.length){state.rounds.forEach(r=>{r.results=r.results.filter(c=>engine.docs.has(c.doc_id))});$('#query').value=state.query;Object.entries(state.conditions||{}).forEach(([k,v])=>{const id={destination:'destination',date:'trade-date',origin:'origin',commodity:'commodity'}[k];if(id)$('#'+id).value=v});render();renderPath()}}catch(error){$('#corpus-status').textContent='资料库不可用';$('#timeline').innerHTML=`<p class="error">${escape(error.message)}，请刷新重试。当前没有可用检索结果。</p>`}try{const res=await fetch('/api/status',{signal:AbortSignal.timeout(4000)});if(res.ok){const s=await res.json();model=s.configured===true}}catch{}$('#model-status').textContent=model?'模型回答已接通 · 检索与回答同页保留':'证据检索模式 · 未接通模型回答服务'}init();
